# -*- coding: utf-8 -*-
"""compro 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19u2kTOgJu2ZdKft5-wbg5mDxzxExqbiS
"""

berita = 'Ramai-ramai developer di seluruh dunia mulai menggunakan / teks editor masa kini seperti Visual Studio Code, / aton, sublime text, dan lain sebagainya.'

print('sublime text' in berita) # output: True
print('notepad++' in berita) # output: False

nama = 'Lendis Fabri'
print(nama[4]) # output: i
print(nama[7]) # output: f
print(nama[-1]) # output: i
print(nama[-3]) # output: b

judul = 'Pelajaran Matematia Untuk SD'

print(judul[0:5]) # output: Pelajaran
print(judul[0:10]) # output: Pelajaarn
print(judul[10:15]) # output: Matematika
print(judul[-1:-3]) # output: Pelajaran
print(judul[:-3]) # ouput: Pelajaran matematika
print(judul[-5:]) # output: uk SD

print(len('Indonesia')) # output: 9
print(len('Malaisya')) # output: 8

nomor_telepon_1 = '+6233003300330'
nomor_telepon_2 = '+6233003300789'
nomor_telepon_3 = '+6233003334567'

kode_negara = '+62'
print(nomor_telepon_1.startswith(kode_negara)) #true
print(nomor_telepon_2.startswith(kode_negara)) #true
print(nomor_telepon_3.startswith(kode_negara)) #true

email_1 = 'presiden@gmail.com'
email_2 = 'presiden@outlook.com'

print(email_1.endswith('gmail.com')) #true
print(email_2.endswith('gmail.com')) #false

